# Generated by Django 5.2.16 on 2026-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Platform Super Admin'), ('facility_admin', 'Facility Admin'), ('doctor', 'Doctor')], default='', max_length=20),
        ),
    ]
