# Generated by Django 5.2.16 on 2026-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_super_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Platform Super Admin'), ('facility_admin', 'Facility Admin'), ('staff', 'Facility Staff'), ('doctor', 'Doctor')], default='', max_length=20),
        ),
    ]
