# Generated by Django 5.2.16 on 2026-08-22 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')]),
        ),
    ]
