# Generated by Django 5.2.16 on 2026-09-14 07:46

import core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_role_permission_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
