# Generated by Django 5.2.16 on 2026-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_slug_alter_affiliationschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraffiliation',
            name='consultation_type',
            field=models.CharField(choices=[('In-patient', 'In-patient'), ('Chamber', 'Chamber'), ('Doctor', 'Doctor'), ('OPD', 'OPD')], default='Chamber', max_length=50),
        ),
    ]
