# Generated by Django 5.2.16 on 2026-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bmdc_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
