# Generated by Django 5.2.16 on 2026-08-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoraffiliation',
            name='consultation_type',
        ),
    ]
