# Generated by Django 5.2.16 on 2026-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctoraffiliation_consultation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
