# Generated by Django 5.2.16 on 2026-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='academic_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
