# Generated by Django 5.2.16 on 2026-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctor_academic_title_doctor_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
