# Generated by Django 5.2.16 on 2026-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/images/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.9, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, default=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='doctoraffiliation',
            name='chamber_type',
            field=models.CharField(blank=True, default='Primary Chamber', max_length=100),
        ),
        migrations.AddField(
            model_name='doctoraffiliation',
            name='status_label',
            field=models.CharField(blank=True, default='Available Today', max_length=100),
        ),
    ]
