# Generated by Django 5.2.16 on 2026-09-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctor_gender_doctor_image_doctor_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinical_services',
            field=models.TextField(blank=True, default='', help_text='Clinical services offered by the doctor'),
        ),
    ]
