# Generated by Django 5.2.16 on 2026-09-13 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_remove_doctor_description_doctor_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecialty',
            name='bn_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='canonical_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='For compound specialties: the canonical specialties it covers. For simple ones: just itself.', related_name='compound_specialties', to='doctors.doctorspecialty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctorspecialty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SpecialtyAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('normalized', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(blank=True, choices=[('bn', 'Bengali'), ('en', 'English')], max_length=2)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='doctors.doctorspecialty')),
            ],
            options={
                'verbose_name': 'Specialty Alias',
                'verbose_name_plural': 'Specialty Aliases',
                'constraints': [models.UniqueConstraint(fields=('normalized',), name='uniq_alias_global')],
            },
        ),
    ]
