# Generated by Django 5.2.16 on 2026-09-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_doctorspecialty_bn_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialty',
            name='canonical_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
