# Generated by Django 5.2.16 on 2026-09-14 07:46

import core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctorspecialty_canonical_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationschedule',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctoraffiliation',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorspecialty',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialtyalias',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
