# Generated by Django 5.2.16 on 2026-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_alter_affiliationschedule_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bn_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='old_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
