# Generated by Django 5.2.16 on 2026-09-27 18:07

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_doctor_bn_name_doctor_old_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('physician', 'Physician'), ('dental', 'Dental'), ('allied', 'Allied Health'), ('alternative', 'Alternative Medicine'), ('', 'Unspecified')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='formal_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='is_umbrella',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, related_name='subspecialties', to='doctors.doctorspecialty'),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('physician', 'Physician'), ('dental', 'Dental'), ('allied', 'Allied Health'), ('alternative', 'Alternative Medicine'), ('', 'Unspecified')], default='physician', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='related',
            field=models.ManyToManyField(blank=True, to='doctors.doctorspecialty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('', 'Unspecified')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='LegacySpecialtySlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_slugs', to='doctors.doctorspecialty')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialtyClaim',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('text_bn', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(choices=[('card', 'Card'), ('brochure', 'Brochure'), ('bmdc', 'BMDC'), ('self', 'Self-reported'), ('admin', 'Admin'), ('legacy', 'Legacy DB tags')], max_length=20)),
                ('source_ref', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('approved', 'Approved'), ('flagged', 'Flagged'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_claims', to='doctors.doctor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='claims', to='doctors.doctorspecialty')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'source', 'source_ref', 'order'), name='uniq_claim_slot'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('doctor',), name='one_primary_claim')],
            },
        ),
    ]
