# Generated by Django 5.2.16 on 2026-09-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_taxonomy_v3_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorspecialty',
            name='components',
        ),
    ]
