# Generated by Django 5.2.16 on 2026-09-29 15:07

import core.uuid7
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_backfill_specialty_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoraffiliation',
            name='status_label',
        ),
        migrations.AddField(
            model_name='affiliationschedule',
            name='avg_consult_minutes',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='affiliationschedule',
            name='max_patients',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='doctoraffiliation',
            name='advance_booking_days',
            field=models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.doctorspecialty'),
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('cancel', 'Cancel'), ('modify', 'Modify'), ('extra', 'Extra')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('max_patients', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('avg_consult_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='doctors.doctoraffiliation')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='doctors.affiliationschedule')),
            ],
            options={
                'ordering': ['date', 'start_time', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('affiliation', 'date', 'schedule'), name='uniq_exception_per_session_date')],
            },
        ),
    ]
