# Generated by Django 5.2.16 on 2026-09-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0022_remove_doctoraffiliation_status_label_and_more'),
        ('facilities', '0019_add_hospital_details_reviewed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctoraffiliation',
            constraint=models.UniqueConstraint(fields=('doctor', 'location'), name='unique_doctor_location'),
        ),
    ]
