# Generated by Django 5.2.16 on 2026-10-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_doctoraffiliation_unique_doctor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraffiliation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
