# Generated by Django 5.2.16 on 2026-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_streamline_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecialty',
            name='related_leaves',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='doctors.doctorspecialty'),
        ),
    ]
