services:
  - type: web
    name: doctors-hub
    runtime: python
    region: singapore
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn --chdir doctors_hub_backend core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_R5MJvdxXQ7GP@ep-late-breeze-azx4qvya-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
