# Generated by Django 5.2.16 on 2026-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbooking',
            name='address',
        ),
        migrations.AddField(
            model_name='labbooking',
            name='pickup_address_line',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='pickup_area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='pickup_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='pickup_district',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='labbooking',
            name='patient_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
