# Generated by Django 5.2.16 on 2026-08-22 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_doctorbooking_patient_phone_alter_doctorbooking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbooking',
            name='patient_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='labbooking',
            name='patient_phone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')]),
        ),
    ]
