# Generated by Django 5.2.16 on 2026-09-02 07:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_doctorbooking_patient_phone_and_more'),
        ('doctors', '0009_alter_doctor_is_verified'),
        ('facilities', '0012_remove_diagnosticcentercategory_parent_and_more'),
        ('tests', '0002_remove_facilitytest_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalServiceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField()),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_phone', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')])),
            ],
            options={
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')])),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(default='booking', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')])),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField()),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_phone', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi number (e.g. '01712345678' or '+8801712345678').", regex='^(?:\\+8801|8801|01)[3-9]\\d{8}$')])),
                ('pickup_address_line', models.CharField(default='', max_length=300)),
                ('pickup_area', models.CharField(blank=True, default='', max_length=100)),
                ('pickup_city', models.CharField(blank=True, default='', max_length=100)),
                ('pickup_district', models.CharField(default='Dhaka', max_length=100)),
            ],
            options={
                'ordering': ['-pickup_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='labbooking',
            name='facility_test',
        ),
        migrations.RemoveField(
            model_name='labbooking',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='doctorbooking',
            options={'ordering': ['date', 'serial_number', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='doctorbooking',
            name='unique_doctor_slot',
        ),
        migrations.RemoveField(
            model_name='doctorbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='booked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalservicebooking',
            name='booked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalservicebooking',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='facilities.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalservicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facilities.hospitalservice'),
        ),
        migrations.AddField(
            model_name='hospitalservicebooking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='bookings.patient'),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='bookings.patient'),
        ),
        migrations.AddConstraint(
            model_name='doctorbooking',
            constraint=models.UniqueConstraint(fields=('affiliation', 'date', 'serial_number'), name='unique_doctor_date_serial'),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='booked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='facility_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tests.facilitytest'),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='bookings.patient'),
        ),
        migrations.DeleteModel(
            name='LabBooking',
        ),
    ]
