# Generated by Django 5.2.16 on 2026-09-14 07:46

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_hospitalservicebooking_otpverification_patient_and_more'),
        ('facilities', '0018_remove_location_facilities__distric_d12a14_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='pickup_thana',
            field=models.ForeignKey(blank=True, help_text='Canonical administrative Thana/Upazila for sample pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_bookings', to='facilities.thana'),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospitalservicebooking',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
