# Generated by Django 5.2.16 on 2026-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_testbooking_pickup_thana_alter_doctorbooking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbooking',
            name='pickup_area',
        ),
        migrations.RemoveField(
            model_name='testbooking',
            name='pickup_city',
        ),
        migrations.RemoveField(
            model_name='testbooking',
            name='pickup_district',
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='pickup_address_line',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
