# Generated by Django 5.2.16 on 2026-09-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_testbooking_pickup_area_and_more'),
        ('doctors', '0022_remove_doctoraffiliation_status_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctorbooking',
            name='unique_doctor_date_serial',
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='estimated_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_bookings', to='doctors.affiliationschedule'),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='schedule_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_bookings', to='doctors.scheduleexception'),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='session_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='session_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='doctorbooking',
            constraint=models.UniqueConstraint(fields=('affiliation', 'date', 'session_key', 'serial_number'), name='unique_serial_per_session'),
        ),
    ]
