# Generated by Django 5.2.16 on 2026-09-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_populate_doctorbooking_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorbooking',
            name='slot',
        ),
    ]
