# Generated by Django 5.2.16 on 2026-10-04 04:49

from django.db import migrations, models


def backfill_price_snapshots(apps, schema_editor):
    DoctorBooking = apps.get_model('bookings', 'DoctorBooking')
    TestBooking = apps.get_model('bookings', 'TestBooking')
    for booking in DoctorBooking.objects.select_related('affiliation').iterator():
        DoctorBooking.objects.filter(pk=booking.pk).update(fee_at_booking=booking.affiliation.fee)

    for booking in TestBooking.objects.select_related('facility_test').iterator():
        facility_test = booking.facility_test
        price = facility_test.price
        discount = facility_test.discount_percent or 0
        discounted_price = None if price is None else price - (price * discount / 100)
        TestBooking.objects.filter(pk=booking.pk).update(
            price_at_booking=discounted_price,
            home_charge_at_booking=(facility_test.home_sample_charge if booking.collection_type == 'home' else None),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_canonicalize_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbooking',
            name='fee_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='collection_type',
            field=models.CharField(choices=[('center', 'Center'), ('home', 'Home')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='home_charge_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_price_snapshots, migrations.RunPython.noop),
    ]
