# Generated by Django 5.2.16 on 2026-08-13 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='FlaskConical', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='Building2', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='Activity', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line', models.CharField(max_length=300)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['district'], name='facilities__distric_6393fe_idx'), models.Index(fields=['division'], name='facilities__divisio_bb1b40_idx')],
            },
        ),
        migrations.CreateModel(
            name='PracticeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('hospital', 'Hospital'), ('diagnostic_center', 'Diagnostic Center'), ('chamber', 'Chamber')], max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facilities/logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/images/')),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('open_timing', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='facilities.address')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticCenterCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facilities.diagnosticcentercategory')),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chamber_detail', serialize=False, to='facilities.practicelocation')),
                ('assistant_phone', models.CharField(blank=True, max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticCenter',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='diagnostic_center_detail', serialize=False, to='facilities.practicelocation')),
                ('categories', models.ManyToManyField(blank=True, related_name='centers', to='facilities.diagnosticcentercategory')),
                ('services', models.ManyToManyField(blank=True, related_name='centers', to='facilities.diagnosticservice')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital_detail', serialize=False, to='facilities.practicelocation')),
                ('has_diagnostic_center', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='hospitals', to='facilities.hospitalcategory')),
                ('services', models.ManyToManyField(blank=True, related_name='hospitals', to='facilities.hospitalservice')),
            ],
        ),
        migrations.AddIndex(
            model_name='practicelocation',
            index=models.Index(fields=['location_type'], name='facilities__locatio_7da79a_idx'),
        ),
    ]
