# Generated by Django 5.2.16 on 2026-08-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_slug_alter_affiliationschedule_day_of_week'),
        ('facilities', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeLocation',
            new_name='Location',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='facilities__locatio_cebd0c_idx',
            old_name='facilities__locatio_7da79a_idx',
        ),
        migrations.RemoveField(
            model_name='diagnosticcenter',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='categories',
        ),
        migrations.AddField(
            model_name='diagnosticcenter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='facilities.diagnosticcentercategory'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='facilities.hospitalcategory'),
        ),
    ]
