# Generated by Django 5.2.16 on 2026-08-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_rename_practicelocation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='address_line',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='division',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['district'], name='facilities__distric_a45575_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['division'], name='facilities__divisio_ad4671_idx'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
