# Generated by Django 5.2.16 on 2026-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_location_address_location_address_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticcentercategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='diagnosticcentercategory',
            name='icon',
            field=models.CharField(blank=True, default='Building2', max_length=100),
        ),
    ]
