# Generated by Django 5.2.16 on 2026-08-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_diagnosticcentercategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='facilities__distric_a45575_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='facilities__divisio_ad4671_idx',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='diagnosticcentercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facilities.diagnosticcentercategory'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnosticcentercategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(max_length=100),
        ),
    ]
