# Generated by Django 5.2.16 on 2026-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facilitymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['district', 'division'], name='facilities__distric_d12a14_idx'),
        ),
    ]
