# Generated by Django 5.2.16 on 2026-08-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_location_area_alter_location_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ownership_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('other', 'Other')], default='private', max_length=20),
        ),
    ]
