# Generated by Django 5.2.16 on 2026-08-23 10:24

from django.db import migrations

def forwards_func(apps, schema_editor):
    DiagnosticCenter = apps.get_model("facilities", "DiagnosticCenter")
    for dc in DiagnosticCenter.objects.select_related('category', 'location').all():
        if dc.category and dc.category.name.lower() == 'government':
            dc.location.ownership_type = 'government'
        else:
            dc.location.ownership_type = 'private'
        dc.location.save(update_fields=['ownership_type'])

    # Clear out DiagnosticCenterCategory since it's just 'Private' and 'Government'
    DiagnosticCenterCategory = apps.get_model("facilities", "DiagnosticCenterCategory")
    DiagnosticCenterCategory.objects.all().delete()

def backwards_func(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_location_ownership_type'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
