# Generated by Django 5.2.16 on 2026-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_update_diagnostic_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ownership_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government')], default='private', max_length=20),
        ),
    ]
