# Generated by Django 5.2.16 on 2026-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_alter_location_ownership_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilityMembership',
        ),
    ]
