# Generated by Django 5.2.16 on 2026-09-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_delete_facilitymembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticcentercategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='hospitalservice',
            name='diagnostic_services',
            field=models.ManyToManyField(blank=True, related_name='hospital_services', to='facilities.diagnosticservice'),
        ),
    ]
