# Generated by Django on 2026-09-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_remove_diagnosticcentercategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalservice',
            name='diagnostic_services',
        ),
    ]
