# Generated by Django 5.2.16 on 2026-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_remove_hospitalservice_diagnostic_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ownership_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('hospital_affiliated', 'Hospital Affiliated Lab'), ('ngo', 'NGO / Non-Profit Laboratory')], default='private', max_length=20),
        ),
    ]
