# Generated by Django 5.2.16 on 2026-09-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_alter_location_ownership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='accreditation',
            field=models.CharField(blank=True, default='JCI Accredited Facility', max_length=150),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulance_phone',
            field=models.CharField(blank=True, default='+880 1700-000000', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bed_capacity',
            field=models.IntegerField(default=650),
        ),
        migrations.AddField(
            model_name='hospital',
            name='dghs_reg_no',
            field=models.CharField(blank=True, default='DGHS Reg #H-098234', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_phone',
            field=models.CharField(blank=True, default='10678', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_helipad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds_available',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds_total',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ot_suites_count',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='hospital',
            name='parking_capacity',
            field=models.CharField(blank=True, default='280 Car Parking Available', max_length=100),
        ),
    ]
