# Generated by Django 5.2.16 on 2026-09-14 07:39

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_hospital_accreditation_hospital_ambulance_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='English name (e.g. Dhaka)', max_length=50, unique=True)),
                ('bn_name', models.CharField(blank=True, help_text='Bengali name (e.g. ঢাকা)', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='diagnosticcentercategory',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticservice',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospitalcategory',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospitalservice',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='English name (e.g. Gazipur)', max_length=50)),
                ('bn_name', models.CharField(blank=True, help_text='Bengali name (e.g. গাজীপুর)', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='facilities.division')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('division', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='English name (e.g. Dhanmondi, Savar)', max_length=100)),
                ('bn_name', models.CharField(blank=True, help_text='Bengali name (e.g. ধানমন্ডি)', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='facilities.district')),
            ],
            options={
                'verbose_name': 'Thana / Upazila',
                'verbose_name_plural': 'Thanas / Upazilas',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='thana',
            field=models.ForeignKey(blank=True, help_text='Canonical Thana/Upazila where this facility is located.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='facilities.thana'),
        ),
    ]
