# Generated by Django 5.2.16 on 2026-09-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0017_backfill_location_thana'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='facilities__distric_d12a14_idx',
        ),
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.RemoveField(
            model_name='location',
            name='division',
        ),
        migrations.AlterField(
            model_name='location',
            name='thana',
            field=models.ForeignKey(help_text='Canonical Thana/Upazila where this facility is located.', on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='facilities.thana'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['thana'], name='facilities__thana_i_e37843_idx'),
        ),
    ]
