# Generated by Django 5.2.16 on 2026-09-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_remove_location_facilities__distric_d12a14_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='details_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
