# Generated by Django 5.2.16 on 2026-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0019_add_hospital_details_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalcategory',
            name='count',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='accreditation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ambulance_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='dghs_reg_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='has_helipad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ot_suites_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='parking_capacity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
