# Generated by Django 5.2.16 on 2026-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytest',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='facilitytest',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='facilitytest',
            name='original_price',
        ),
        migrations.AddField(
            model_name='facilitytest',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
