# Generated by Django 5.2.16 on 2026-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_facilitytest_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytest',
            name='home_sample_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facilitytest',
            name='home_sample_note',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
