# Generated by Django 5.2.16 on 2026-09-14 07:46

import core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_facilitytest_home_sample_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytest',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='id',
            field=models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
