# Generated by Django 5.2.16 on 2026-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_facilitytest_id_alter_test_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytest',
            name='home_sample_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='facilitytest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
