#!/usr/bin/env python
"""Generate the patient-surface endpoint list in docs/api/VERSIONING.md (plan V.10.1).

The list is generated from core/api_contract.py — never typed by hand. Re-running
the script with an unchanged contract produces no file change (checked by the
Phase 10 gate).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / 'doctors_hub_backend'
DOC = ROOT / 'docs' / 'api' / 'VERSIONING.md'

sys.path.insert(0, str(BACKEND))
from core.api_contract import PATIENT_SURFACE, UNVERSIONED_SURFACE  # noqa: E402

BEGIN = '<!-- surface:begin (generated by scripts/generate_surface_list.py) -->'
END = '<!-- surface:end -->'


def render():
    lines = [BEGIN, '']
    lines.append('| Method | Path |')
    lines.append('| --- | --- |')
    for method, path in PATIENT_SURFACE:
        lines.append(f'| `{method}` | `{path}` |')
    lines.append('')
    lines.append('Unversioned permanent endpoints (decision D4):')
    lines.append('')
    lines.append('| Method | Path |')
    lines.append('| --- | --- |')
    for method, path in UNVERSIONED_SURFACE:
        lines.append(f'| `{method}` | `{path}` |')
    lines.append('')
    lines.append(END)
    return '\n'.join(lines)


def main():
    text = DOC.read_text()
    pattern = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        print(f'error: markers not found in {DOC}', file=sys.stderr)
        return 1
    new_text = pattern.sub(lambda _: render(), text)
    if new_text != text:
        DOC.write_text(new_text)
        print(f'updated {DOC}')
    else:
        print('already up to date')
    return 0


if __name__ == '__main__':
    sys.exit(main())
