# Generated by Django 5.2.16 on 2026-07-27 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('facility_types', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('open_timing', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('services', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.TextField()),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PathologyTest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('fasting_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('report_time', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_tests', to='api.branch')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_at', to='api.pathologytest')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('OPD', 'OPD'), ('In-patient', 'In-patient')], default='OPD', max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_doctors', to='api.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.doctoraffiliation')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.doctoraffiliation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.hospital'),
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.branchtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', to='api.specialty'),
        ),
    ]
