# Generated by Django 5.2.16 on 2026-07-30 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='FlaskConical', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Services',
            },
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='Activity', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Hospital Services',
            },
        ),
        migrations.AddField(
            model_name='diagnosticcenter',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='diagnosticcenter',
            name='services',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='services',
        ),
        migrations.AddField(
            model_name='diagnosticcenter',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='centers', to='api.diagnosticservice'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='api.hospitalservice'),
        ),
    ]
