# Generated by Django 5.2.16 on 2026-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chamber',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
