# Generated by Django 5.2.16 on 2026-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
