# Generated by Django 5.2.16 on 2026-08-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diagnosticservice_hospitalservice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosticcentertest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diagnosticcentertest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_tests', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_diagnostic_center',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diagnosticcentertest',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_tests', to='api.diagnosticcenter'),
        ),
    ]
