# Generated by Django 5.2.16 on 2026-07-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_hospital_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='Stethoscope', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Doctor Specialties',
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecialty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='Building2', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hospital Specialties',
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='FlaskConical', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Test Categories',
            },
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.AddField(
            model_name='branch',
            name='specialty_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', to='api.doctorspecialty'),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='test_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='api.testcategory'),
        ),
    ]
