# Generated by Django 5.2.16 on 2026-08-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_diagnosticcentertest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcategory',
            name='parent',
        ),
    ]
